### ISSUE TITLE
GH Pages - Estrutura

### ISSUE THREAD

**Issue by cyz** [WoMakersCode/networking#1]
Montar uma GH pages que compreenda a seguinte estrutura:

- [x] Menu e header padrão, seguindo o modelo do site womakerscode.org

**Comment by cyz** [comment]
![header](https://user-images.githubusercontent.com/2198735/51445241-1dd60100-1cea-11e9-8e97-ef130eb11308.jpg)
![footer](https://user-images.githubusercontent.com/2198735/51445242-1dd60100-1cea-11e9-93bb-72948039cdf1.jpg)

**Comment by LucianaMarques** [comment]
Oi @cyz, eu gostaria de trabalhar nesta issue se já não tiver ninguém responsável, posso submeter um PR?

**Comment by cyz** [comment]
@LucianaMarques você pode montar essa parte sim!
A @glaucia86 vai trabalhar na parte do gerador estático

**Comment by glaucia86** [comment]
> @LucianaMarques você pode montar essa parte sim!
> A @glaucia86 vai trabalhar na parte do gerador estático, você pode trocar uma ideia com ela :)

Blz. quem vai criar o repo?

**Comment by cyz** [comment]
> > @LucianaMarques você pode montar essa parte sim!
> > A @glaucia86 vai trabalhar na parte do gerador estático, você pode trocar uma ideia com ela :)
> 
> Blz. quem vai criar o repo?

Pode ser esse repo aqui mesmo Glau, só fazer fork e duas branchs pra vocês trabalharem

**Comment by glaucia86** [comment]
> > > @LucianaMarques você pode montar essa parte sim!
> > > A @glaucia86 vai trabalhar na parte do gerador estático, você pode trocar uma ideia com ela :)
> > 
> > 
> > Blz. quem vai criar o repo?
> 
> Pode ser esse repo aqui mesmo Glau, só fazer fork e duas branchs pra vocês trabalharem

show!

**Comment by LucianaMarques** [comment]
@cyz obrigada!
@glaucia86 pode me mandar um e-mail? lucianadacostamarques@gmail.com

**Comment by glaucia86** [comment]
> lucianadacostamarques@gmail.com

Enviado agorinha @LucianaMarques

**Comment by LucianaMarques** [comment]
@glaucia86 opa vou ler!

Ah e preciso nomear minha branch com algum nome específico? Vocês têm algum padrão?

**Comment by glaucia86** [comment]
> @glaucia86 opa vou ler!
> 
> Ah e preciso nomear minha branch com algum nome específico? Vocês têm algum padrão?

coloca o nome da branch seguida da issue.
Ex.: git checkout -b feature-criando-estrutura-site-issue#1 

Se colocar a tralha na branch vai linkar com essa issue aqui ;)

**Comment by glaucia86** [comment]
@cyz e @LucianaMarques concluída a parte do Back-End. Fiz várias modificações relacionadas ao projeto original do Node.js-Generator. E procurei documentar para facilitar quem for fazer as páginas em .md > .html

Peço que, quem for mexer no projeto, dê uma lida antes como está estruturado o projeto e compreender. Caso tenha alguma dúvida, podem me procurar ou abrir uma issue aqui ;)

@cyz habilitei no projeto o Travis. Só que para que eu possa de fato saber se os commits futuros (de PR's e de branchs criadas) estarão dentro do padrão, preciso que você me dê permissão para alterar as configurações desse repo. Se não tiver como, me avisa que te explico como faz - é super piece of cake! :)

Depois criarei regras de commits, nomenclaturas de branchs, criação de um arquivo CHANGELOG.md e regras para aprovação de PR's criadas para o projeto. Visando justamente ficar mais organizado e fácil de manter dentro dos padrões. :)

Dúvidas... podem me contatar. Indo dormir! Bjs!

**Comment by LucianaMarques** [comment]
Obrigada Glaucia!

Dou uma olhada quando chegar em casa!

**Comment by LucianaMarques** [comment]
Estou trabalhando no projeto, preciso entender só como fazer o que a Glaucia pediu utilizando markdown.

**Comment by glaucia86** [comment]
> Estou trabalhando no projeto, preciso entender só como fazer o que a Cynthia pediu utilizando markdown.

Show... tente dar uma olhada nesses dois links:

**[Jekyll](https://jekyllrb.com/)**
**[Markdown-it](https://github.com/markdown-it/markdown-it)**

**Comment by LucianaMarques** [comment]
> > Estou trabalhando no projeto, preciso entender só como fazer o que a Cynthia pediu utilizando markdown.
> 
> Show... tente dar uma olhada nesses dois links:
> 
> **[Jekyll](https://jekyllrb.com/)**

Qual o outro link?

Eu acho que o Markdown tem algumas limitações de definir tamanho de imagem e inserir uma navbar. Eu poderia gerar uma página com o Markdown e depois manualmente mexer no html e ver se o site funciona. Mas daí acho que pode dar problema sempre que alguém quiser mexer na página original (suponho que teria que inserir tudo não gerado a partir do markdown de novo). Alguma alternativa?

**Comment by glaucia86** [comment]
> > > Estou trabalhando no projeto, preciso entender só como fazer o que a Cynthia pediu utilizando markdown.
> > 
> > 
> > Show... tente dar uma olhada nesses dois links:
> > **[Jekyll](https://jekyllrb.com/)**
> 
> Qual o outro link?
> 
> Eu acho que o Markdown tem algumas limitações de definir tamanho de imagem e inserir uma navbar. Eu poderia gerar uma página com o Markdown e depois manualmente mexer no html e ver se o site funciona. Mas daí acho que pode dar problema sempre que alguém quiser mexer na página original (suponho que teria que inserir tudo não gerado a partir do markdown de novo). Alguma alternativa?

Faz o seguinte... gera um arquivo teste.md e rode aquele script q te falei. Depois ele vai gerar um teste.html

Depois de gerar um .html, comece a fazer as mudanças no arquivo .html e vê se vai funfar ;)
Se não funfar... use o Jekyll.

@cyz alguma outra sugestão a dar para a @LucianaMarques ?

**Comment by LucianaMarques** [comment]
> > > > Estou trabalhando no projeto, preciso entender só como fazer o que a Cynthia pediu utilizando markdown.
> > > 
> > > 
> > > Show... tente dar uma olhada nesses dois links:
> > > **[Jekyll](https://jekyllrb.com/)**
> > 
> > 
> > Qual o outro link?
> > Eu acho que o Markdown tem algumas limitações de definir tamanho de imagem e inserir uma navbar. Eu poderia gerar uma página com o Markdown e depois manualmente mexer no html e ver se o site funciona. Mas daí acho que pode dar problema sempre que alguém quiser mexer na página original (suponho que teria que inserir tudo não gerado a partir do markdown de novo). Alguma alternativa?
> 
> Faz o seguinte... gera um arquivo teste.md e rode aquele script q te falei. Depois ele vai gerar um teste.html
> 
> Depois de gerar um .html, comece a fazer as mudanças no arquivo .html e vê se vai funfar ;)
> Se não funfar... use o Jekyll.
> 
> @cyz alguma outra sugestão a dar para a @LucianaMarques ?

Então, mas mudar o .html depois de rodar o script acho que ainda acarreta o mesmo problema de se alguém precisar mudar a página e rodar o script de novo pode dar problema. 

O que precisa ter na navbar de cima? Um 'sobre' e 'voluntárias'?

Obrigada!

**Comment by glaucia86** [comment]
> > > > > Estou trabalhando no projeto, preciso entender só como fazer o que a Cynthia pediu utilizando markdown.
> > > > 
> > > > 
> > > > Show... tente dar uma olhada nesses dois links:
> > > > **[Jekyll](https://jekyllrb.com/)**
> > > 
> > > 
> > > Qual o outro link?
> > > Eu acho que o Markdown tem algumas limitações de definir tamanho de imagem e inserir uma navbar. Eu poderia gerar uma página com o Markdown e depois manualmente mexer no html e ver se o site funciona. Mas daí acho que pode dar problema sempre que alguém quiser mexer na página original (suponho que teria que inserir tudo não gerado a partir do markdown de novo). Alguma alternativa?
> > 
> > 
> > Faz o seguinte... gera um arquivo teste.md e rode aquele script q te falei. Depois ele vai gerar um teste.html
> > Depois de gerar um .html, comece a fazer as mudanças no arquivo .html e vê se vai funfar ;)
> > Se não funfar... use o Jekyll.
> > @cyz alguma outra sugestão a dar para a @LucianaMarques ?
> 
> Então, mas mudar o .html depois de rodar o script acho que ainda acarreta o mesmo problema de se alguém precisar mudar a página e rodar o script de novo pode dar problema.
> 
> O que precisa ter na navbar de cima? Um 'sobre' e 'voluntárias'?
> 
> Obrigada!

Vamos pensar como um MVP... crie o html apartado desse projeto. Coisa simples. Acho q será melhor para ti. Daí depois vejo com a @cyz como podemos migrar para o projeto no Back-End. O que acha?

**Comment by LucianaMarques** [comment]
> 
> Vamos pensar como um MVP... crie o html apartado desse projeto. Coisa simples. Acho q será melhor para ti. Daí depois vejo com a @cyz como podemos migrar para o projeto no Back-End. O que acha?

@glaucia86 ok, acho que pode ser assim por enquanto!

Minha vontade é gerar sim um MVP e depois ver se consigo modificar os scripts pra fazer exatamente o que queremos! Como acho que isso demoraria um certo tempo, vou me concentrar em gerar a página com os requisitos iniciais aqui e depois incrementamos o projeto em si.

Obrigada :)

**Comment by glaucia86** [comment]
> > Vamos pensar como um MVP... crie o html apartado desse projeto. Coisa simples. Acho q será melhor para ti. Daí depois vejo com a @cyz como podemos migrar para o projeto no Back-End. O que acha?
> 
> @glaucia86 ok, acho que pode ser assim por enquanto!
> 
> Minha vontade é gerar sim um MVP e depois ver se consigo modificar os scripts pra fazer exatamente o que queremos! Como acho que isso demoraria um certo tempo, vou me concentrar em gerar a página com os requisitos iniciais aqui e depois incrementamos o projeto em si.
> 
> Obrigada :)

Show. Monta o html e css. Daí quando finalizar... a gente vê como faz para colocar naquele projeto. Enquanto isso, vou pesquisando algo a respeito. Encontrando aqui... te passo. ;)
Obrigada Lu! :)

**Comment by cyz** [comment]
Estrutura criada e com responsividade testada

**Comment by glaucia86** [comment]
> Estrutura criada e com responsividade testada

LGTM 👍

**Comment by cyz** [comment]
@glaucia86 o que é LGTM?
