### ISSUE TITLE
GH Pages: Perfil da Voluntária

### ISSUE THREAD

**Issue by cyz** [WoMakersCode/networking#3]
A página de perfil da voluntária deverá conter os seguintes campos:

- [x] Foto
- [x] Nome
- [x] Cidade / Estado
- [x] Biografia
- [x] Links de redes sociais
- [x] Tags (o que ela faz para comunidade)
- [x] Projetos em que trabalhou (a voluntária poderá submeter mensalmente PRs para registrar os projetos que ela fez, como organização de meetup, palestra ou artigo)

**Comment by cyz** [comment]
Modelo de página:

![image](https://user-images.githubusercontent.com/2198735/51445367-35fa5000-1ceb-11e9-9614-d3d60ea72acc.png)

**Comment by glaucia86** [comment]
Mudou para jekyll @cyz ?

**Comment by cyz** [comment]
Oi @glaucia86!

Sim, mudei a stack para Jekyll para terminar a estrutura mais rápido e conseguir ter a webapp pronta para março.

abs,
